my_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from shaozi_blog.views import index,errortest
app_name='my_blog'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index,name='index'),
    url(r'^shaozi/',include('shaozi_blog.urls'),name='shaozi'),
]

shaozi_blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'shaozi_blog'
urlpatterns = [
    url(r'^$',views.index),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^(?P<cate>\w+)/$',views.category , name='category'),
    url(r'^article/(?P<pk>[0-9]+)/$'
         ,views.article,name='article'),
]

shaozi_blog/models.py
from django.db import models
import os
from django.conf import settings

def get_article_content_path(instance,filename):
<<<<<<< HEAD
    return 'article/{0}/{1}'.format(
            instance.title,filename)
def get_article_image_comtent_path(instance,filename):
    return 'article/{0}/{1}'.format(
            instance.articles.title,filename)
=======

    if instance.article_id is not None :
        return 'article/{0}/{1}'.format(
                str(instance.article_id),filename)

    return 'article/{0}/{1}'.format(
            instance.tmp_dir,filename)

def get_article_image_comtent_path(instance,filename):

    if instance.articles.article_id is not None :
        return 'article/{0}/{1}'.format(
                str(instance.articles.article_id),filename)
>>>>>>> af1662806ecd6fcd697af8d8786b1030b37f3745

class Language(models.Model):
    color_choice=(
            ('NBLUE','normal_blue'),
            ('RED','red'),
            ('GRAY','gray'),
            ('GREEN','green'),
            ('SBLUE','sky_blue'),
            ('YELLOW','yellow'),
            )

    name=models.CharField(max_length=30,blank=False)
    color=models.CharField(max_length=8,
            choices=color_choice,
            default='NBLUE'
            )
    def __str__(self):
        return self.name

class Category(models.Model):
#The name should match the url (dict of views.model_cate_to_chinese)
    cate_to_html={'toy':'有趣','internet':'计算机网络',
            'data_aglo':'数据结构与算法','notes':'课程笔记',}
    cate_choice=(
            ('toy','toy'),
            ('internet','intetnet'),
            ('data_aglo','datastructure and alogrithms'),
            ('notes','some notes'),
            )


    category_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=40,choices=cate_choice,blank=False,null=False)
    article_num=models.IntegerField(default=0)
    language=models.ManyToManyField(Language)
    permission=models.CharField(max_length=20,null=False,blank=True,default='')

    def model_cate_to_chinese(self):
        return Category.cate_to_html[self.name]
    model_cate_to_chinese.short_description='分类名称'
    def __str__(self):
        return self.name

class Articles(models.Model):
    child_dir='article'
    #author,title and path can't be blank
    article_id=models.AutoField(primary_key=True)

    category=models.ManyToManyField(Category)
    language=models.ManyToManyField(Language)
    permission=models.CharField(max_length=10,null=False,blank=True,default='')

    author=models.ForeignKey('Author',on_delete=models.SET_NULL,
            blank=False,null=True)
    title=models.CharField(max_length=40,null=False,blank=False)
    submit_date=models.DateTimeField(auto_now_add=True)

    path=models.FileField(upload_to=get_article_content_path,blank=False)
    description=models.CharField(max_length=200,null=False,blank=True,default='nothing here')
#need rebuild
    @property
    def tmp_dir(self):
        if hasattr(self,'_tmp_dir'):
            return self._tmp_dir
        else:
            self._tmp_dir=self._create_tmpn_dir('article')
        return self._tmp_dir

    @tmp_dir.setter
    def tmp_dir(self,value):
        self._tmp_dir=value
        return self._tmp_dir

   #contentImage_set
    def __str__(self):
        return self.title

    def _create_tmpn_dir(self,child_dir):
        """1 child_dir should not start with '/' or end with '/'
           2 mkdir  MEDIA_ROOT/child_dir/tmpn                """

        if settings.MEDIA_ROOT[-1]=='/':
            cwd=settings.MEDIA_ROOT+child_dir+'/'
        else:
            cwd=settings.MEDIA_ROOT+'/'+child_dir+'/'

        num=0
        while True:
            dir_path=os.path.join(cwd,'tmp'+str(num))
            if not os.path.exists(dir_path):
                try:
                    os.makedirs(dir_path)
                except FileExistsError :
                    num+=1
                    continue
                return os.path.split(dir_path)[1]
            else :
                num+=1
                continue

    def time_for_html(self):
        return self.submit_date.strftime('%Y - %m - %d')
    class meta:
        ordering=['submit_date']

class Author(models.Model):
    #name of Author can't be blank.
    author_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=40,null=False,blank=False)
    description=models.CharField(max_length=100,null=False,blank=True)

    def __str__(self):
        return self.name
class ContentImage(models.Model):
    content_image=models.ImageField(upload_to=get_article_image_comtent_path)
    articles=models.ForeignKey(Articles)

    def __str__(self):
        return str(self.articles.article_id)
    __str__.short_description='related_article_id'
 #Create your models here.

shaozi_blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.template import Template

from shaozi_blog import models
from django.http import Http404
from django.template import Context


"""
def model_lebal_to_bootstrap_style(articles):
#transmit color to bootstrap-style for template
#this dict to bootstrap is stupied. rebuild it in the future
    color_to_html={'b':'primary','a':'default','g':'success'
            ,'sb':'info','y':'warining','r':'danger'}
    for an_article in articles:
        an_article.lang=[]
        if an_article.language:
            for a_label in an_article.language.split(';'):
            #str.split will add an extra '' if
            #the split sign is not followed with word
                if a_label !='':
                    color_and_lang=a_label.split(':')
                    color_and_lang[0]=color_to_html[color_and_lang[0]]
                    an_article.lang.append(tuple(color_and_lang))
    return
"""



def model_lebal_to_bootstrap_style(articles):
#add .color_bootstrap attribute to an_article
    color_to_bootstrap={
            'NBLUE':'primary',
            'GRAY':'default',
            'SBLUE':'info',
            'YELLOW':'warning',
            'RED':'danger',
            'GREEN':'success'
            }
    for an_article in articles:
        an_article.lang=[]
        if an_article.language.all().exists():
            all_language=an_article.language.all()
            for a_language in all_language:
                an_article.lang+=[(color_to_bootstrap[a_language.color],a_language.name)]

    return

def index(request):
    recent_articles=models.Articles.objects.all()[0:5]
    if recent_articles.count()!=0:
        model_lebal_to_bootstrap_style(recent_articles)
        return render(request,template_name='shaozi_blog/index.html',
                context={'article_set':recent_articles,})
    return render(request,template_name='shaozi_blog/index.html')

def category(request,cate):

    category=get_object_or_404(models.Category,name=cate)
    article_set=category.articles_set.all()
    model_lebal_to_bootstrap_style(article_set)

    return render(request,
        template_name='shaozi_blog/category.html',
        context={'article_set':article_set,'cate':category.model_cate_to_chinese(),})

def article(request,pk):
#the an_article_set is stupid to fit the model_lebal_to_bootstrap_style func
#and needed  rebuilded
#rebuild for loop  in this block to a tag/fountion
    try:
        an_article_set=models.Articles.objects.filter(article_id=pk)

        model_lebal_to_bootstrap_style(an_article_set)

        an_article=an_article_set[0]
        content=an_article_set[0].path.readlines()
        an_article_set[0].path.close()
        flag=0
        for line in content:
            if line.lstrip().startswith(b'***'):
                line=line.replace(b'***',b'   ',1)
                content[flag]=Template(line).render(Context({'article_id':str(an_article.article_id)}),)
            flag+=1

    except IndexError :
        raise Http404
    return render(request,
        template_name='shaozi_blog/article.html',
        context={'an_article':an_article,'content':content})


def profile(request):
    return render(request,template_name='shaozi_blog/base.html')

#only for test
def errortest(request):
    return render(request,template_name='404.html')
# Create your views here.

shaozi_blog/templates/shaozi_blog/article.html
{% extends "shaozi_blog/base.html" %}
{% load static %}
{% block title %}
{{ an_article.title }}
{% endblock %}

{% block description %}
{{ an_article.description }}
{% endblock %}

{% block different_css %} 
<link rel="stylesheet" href="{% static 'shaozi_blog/css/style_for_article.css' %}" type="text/css">
{% endblock %}



{% block prettyPrint_onload %}
onload="PR.prettyPrint()"
{% endblock %}

{% block prettyPrint_script %}
<script type="text/javascript" src="//cdn.bootcss.com/prettify/188.0.0/prettify.js"></script>
{% endblock %}
 
{% block main %}
  <div class="article">
    <h1 class="text-center">{{ an_article.title }}</h1>  
    <h2>{{ an_article.author }} {{ an_article.time_for_html }} </h2>
      <div class="row margin_bottom_for_lebal">
        <div class="col-xs-10">
        {% for color , lebal in an_article.lang %}
          <span class="label label-{{ color }} for_block">{{ lebal|safe }}</span>
        {% endfor %}
        </div>
      </div>
      {% for i in content %}
        {{ i|safe }}
      {% endfor %}
  </div>
{% endblock %}

shaozi_blog/templates/shaozi_blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block head_title %}勺子的博客{% endblock %}</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="generator" content="Bluefish 2.2.7" >
<meta name="author" content="ss" >
<meta name="keywords" content="勺子 博客">

<meta name="description" content="{% block description %}勺子的博客{% endblock %}">

<meta name="ROBOTS" content="NOINDEX, NOFOLLOW">
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8">
<meta http-equiv="content-style-type" content="text/css">
<link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<!--<link rel="stylesheet" href="{% static 'shaozi_blog/css/bootstrap.css' %}"  type="text/css">-->
<link rel="stylesheet" href="{% static 'shaozi_blog/css/base.css' %}" type="text/css">
{% block different_css %} {% endblock %}

</head>

<body {% block prettyPrint_onload %}{% endblock %}>
  <script src="//cdn.bootcss.com/jquery/3.1.1/jquery.js"></script>
  <script src="//cdn.bootcss.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
  {% block prettyPrint_script %}{% endblock %}
  <div class="navbar navbar-inverse nomargin">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle " data-toggle="collapse" data-target="#blog_navbar_collapse" aria-expanded="false">
          <span class="icon-bar"></span>  
          <span class="icon-bar"></span> 
          <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand" href="/">勺子</a>
      </div>
  
      <div class="collapse navbar-collapse" id="blog_navbar_collapse">
        <ul class="nav navbar-nav navbar-right" >
         
          <li><a href="/shaozi/toy/">有趣</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="ture" aria-expanded="false">计算机<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/shaozi/data_aglo/"><h4>数据结构与算法</h4></a></li>
              <li><a href="/shaozi/internet/"><h4>计算机网络</h4></a></li>
            </ul>
          </li>
          <li><a href="/shaozi/notes/">课程笔记</a></li>
          <li><a href="/shaozi/profile/">关于我</a></li>
        </ul>
      </div>
    </div>  
  </div>
  {% block big_title %}
  {% endblock %}
  <div class="main">
	  <div class="container">
	    <div class="row">
	      <div class="col-md-9"> 
		      {% block main %}
		      <a id="info_nothing" href="/"><h1>这里什么也没有，点我返回主页～</h1></a>
		      {% endblock %}
	      </div>
	      <div class="col-md-3 ">
	        <div class="hidden-xs hidden-sm">
	          <div style="width:100%;height:100px;">
	          </div>
	          <div class="advertisement">
	            <a href="http://www.github.com">
	              <img src="{% static 'shaozi_blog/images/github-logo.png' %}" class="img-thumbnail" alt="图片无法显示">
	            </a>
	          </div>
	          <div class="advertisement">
	            <a href="http://www.stackoverflow.com">
	              <img src="{% static 'shaozi_blog/images/stack.jpg' %}" class="img-thumbnail" alt="图片无法显示">
	            </a>
	          </div>
	        </div>
	        </div>
	      </div>
	    </div>
    </div>
    
  </div>
  <footer class="footer">
   <div class="container">
	    <div class="row">
	      <div class="col-sm-6 col-lg-6">
	      <h3>勺子的博客</h3>
	      </div>
	      <div class="col-sm-6 col-lg-5 col-lg-offset-1">
	        <div class="row">
	          <div class="col-xs-6">
	          <h3>Contributor</h3>
	          <h4>勺子</h4>
	          </div>
	          <div class="col-xs-6">
	          <h3>Framework</h3>
	          <h4>Bootstrap</h4>
	          <h4>Django</h4>
	          </div>
	        </div>
	      </div>
	    </div>
	  </div>
  </footer>

</body>
</html>
</head>

shaozi_blog/templates/shaozi_blog/category.html
{% extends "shaozi_blog/base.html" %}
{% load static %}

{% block title %}
{{ cate }}
{% endblock %}

{% block different_css %}
<link rel="stylesheet" href="{% static 'shaozi_blog/css/style_for_category.css' %}" type="text/css">
{% endblock %}
{% block main %}
<div class="recent_article">
  <div class="category text-center">
    <h1>{{ cate }}</h1>
  </div>
  {% if article_set %}
    {% for article in article_set %}
    <a href="{% url 'shaozi_blog:article' pk=article.article_id %}"><h2>{{ article.title }}</h2></a>
    <h5>{{ article.author.name }} , {{ article.time_for_html }}</h5>
    {% if article.language %}
      <div class="row">
        <div class="col-xs-10" style="margin-bottom :5px;">
          {% for color , language in article.lang %}
            <span class="label label-{{ color }} for_block">{{ language|safe }}</span>
          {% endfor %}
        </div>
      </div>
    {% endif %}
    <p>{{ article.description }}</p>
    <hr>
    {% endfor %}
  {% else %}
    <a id='info_nothing' class='text-center' href="/" ><h1>这里什么也没有，点我返回主页～</h1></a>
  {% endif %}
</div>
{% endblock %}

shaozi_blog/templates/shaozi_blog/index.html
{% extends "shaozi_blog/base.html" %}
{% load static %}
{% block different_css %}
<link rel="stylesheet" href="{% static 'shaozi_blog/css/style_for_index.css' %}" type="text/css">
{% endblock %}

{% block big_title %}
<div class="contain-fluid text-center" id="big_title">
  <div class="row">
    <div class="col-xs-10 col-sm-8 col-xs-offset-1 col-sm-offset-2">
      <h1>欢迎</h1>
      <p>这是一个严肃认真的博客！同时也很有意思！</p>
    </div>
  </div>
</div>
{% endblock %}

{% block main %}
<div class="recent_article">
<h1>最新的文章</h1>
{% for article in article_set %}
  <a href="{% url 'shaozi_blog:article' pk=article.article_id %}"><h2>{{ article.title }}</h2></a>
  <h5>{{ article.author.name }} , {{ article.time_for_html }}</h5>
  {% if article.language %}
    <div class="row">
      <div class="col-xs-10" style="margin-bottom :5px;">
        {% for color , language in article.lang %}
          <span class="label label-{{ color }} for_block">{{ language|safe }}</span>
        {% endfor %}
      </div>
    </div>
  {% endif %}
  <p>{{ article.description }}</p>
  <hr>
{% endfor %}
</div>
{% endblock %}